databases:
  - name: plateformdesuivie-postgres
    databaseName: plateformdesuivie_db
    user: plateformdesuivie_user
    region: frankfurt

services:
  - type: web
    name: plateformdesuivie-its-service
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: plateformdesuivie-postgres
          property: connectionString
      - key: PORT
        value: 10000
    autoDeploy: false